### ISSUE TITLE
Update of image

### ISSUE THREAD

**Issue by vvdaal** [Vlaaaaaaad/gitpod-terraform#15]
I've noticed the cron likely hasn't ran in a while and the image is no longer being updated.
Did you abandon this or just need to fix the ECR image build?

**Comment by Vlaaaaaaad** [comment]
Oops. I stopped using this image (and the folks I know were using it also stopped using it) and somehow GitHub did not email me about the job not running 🤦 Sorry!

I re-enabled the workflow, but I don't plan to actively maintain this — new features, cleanup, upgrades, and other things like that are not something I can allocate time for at the moment.

**Comment by Vlaaaaaaad** [comment]
Yeah, looks like the build is failing and I don't have the bandwidth to look into that so I'll go ahead and archive the repo. Sorry!
