### ISSUE TITLE
Error after pulling the image

### ISSUE THREAD

**Issue by ghost** [Vlaaaaaaad/gitpod-terraform#9]
When I pull the image and test whether terraform is installed correctly using terraform --version. The response is an error message. Do I need to run a configuration script to use the container?

Error message:
cat: /home/linuxbrew/.linuxbrew/Cellar/tfenv/2.0.0/version: No such file or directory
Version could not be resolved (set by /home/linuxbrew/.linuxbrew/Cellar/tfenv/2.0.0/version or tfenv use <version>)

**Comment by Vlaaaaaaad** [comment]
Hey @torstenboe. Apologies, I am rather busy with some personal projects and I don't have any bandwidth to allocate for this right now 😞

I have a feeling GitPod changed some things. Or tfenv did. Or the image settings changed. I am unsure what would be at fault.

I hope I'll get to look at this by the end of the year, but no promises.

**Comment by Vlaaaaaaad** [comment]
Hey @torstenboe, this was fixed in https://github.com/Vlaaaaaaad/gitpod-terraform/pull/10 which came with a big cleanup of the image!

Sorry it took so long.
